version: 3

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    name: rabbit13
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25676:25676"

  config-server:
    build: 
      context: /configserver
    container_name: configserver
    hostname: configserver
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq

  client-service-one:
    build: 
      context: /client-service-one
    hostname: client-server-one
    container_name: client-server-one
    ports:
      - "8081:8081"
    depends_on:
      - config-server

  client-service-two:
    build: 
      context: /client-service-two
    hostname: client-server-two
    container_name: client-server-two
    ports:
      - "8082:8082"
    depends_on:
      - config-server              